import pygame

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
ASPECT_RATIO = (SCREEN_WIDTH / SCREEN_HEIGHT)

TRACK_WIDTH = 5760
TRACK_HEIGHT = 3240

CAR_WIDTH = 80
CAR_HEIGHT = 106

ASSETS_PATH = "Assets"
TRACKS_PATH =  ASSETS_PATH + "/Tracks"
MODELS_PATH = ASSETS_PATH +  "/Models"

# Initialising fonts
FONT_16 = pygame.font.Font(f"{ASSETS_PATH}/Fonts/font.otf", 16)
FONT_32 = pygame.font.Font(f"{ASSETS_PATH}/Fonts/font.otf", 32)
FONT_64 = pygame.font.Font(f"{ASSETS_PATH}/Fonts/font.otf", 64)
FONT_128 = pygame.font.Font(f"{ASSETS_PATH}/Fonts/font.otf", 128)

# Loading car images
BLUE_CAR_IMAGE = pygame.transform.scale(pygame.image.load(f"{ASSETS_PATH}/Cars/BlueCar.png"), (CAR_WIDTH, CAR_HEIGHT))
RED_CAR_IMAGE = pygame.transform.scale(pygame.image.load(f"{ASSETS_PATH}/Cars/RedCar.png"), (CAR_WIDTH, CAR_HEIGHT))

FPS = 60
CAMERA_SCROLL_SPEED = 6

COLOUR_SCHEME = [
    (255, 255, 255),
    (0, 0, 0),
    (31, 102, 31),
    (11, 36, 11),
    (8, 132, 28),
    (255, 0, 0)
]

BACKGROUND_COLOUR = COLOUR_SCHEME[4]

BUTTON_BORDER_THICKNESS = 5
BUTTON_HOVER_THICKNESS = 7

DEFAULT_TRACK_NAME = "track"

CHECKPOINT_FREQUENCY = 5
TOTAL_LAPS = 3
COUNTDOWN_DURATION = 5

NETWORK_INPUT_SIZE = 6
NETWORK_ACTION_SIZE = 9

TRAINING_TIMESTEP = 1 / 10
MAX_IDLE_TIMESTEPS = 10 / TRAINING_TIMESTEP
MAX_TIMESTEPS = int(50 / TRAINING_TIMESTEP)
EXPERIENCE_CAPACITY = int(1000 / TRAINING_TIMESTEP)

SPEED_REWARD = 0.001 * TRAINING_TIMESTEP
CHECKPOINT_REWARD = 0.1
LAP_REWARD = 0.5
CRASH_REWARD = -0.5
IDLE_REWARD = -1

TRAINING_EPISODES = 1000
VISUALISATION_STEP = 10
MAX_VISUALISATION_TIME = 60

BATCH_SIZE = 128
DISCOUNT_FACTOR = 0.99
EXPLORATION_START = 1
EXPLORATION_END = 0.1
EXPLORATION_DECAY = 0.01
TARGET_UPDATE_STRENGTH = 0.1
LR = 1e-4